services:
  # Deploy the broker.
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on: 
      - zookeeper

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb

  django_api:
    # Build using the worker Dockerfile
    build:
      context: ./backend/api_backend
      dockerfile: Dockerfile
    environment:
      rabbitmq_uri: amqp://rabbitmq_server:5672
    depends_on: 
      - postgres_db
      - redis
      - kafka
